# Form implementation generated from reading ui file 'giaodienbaitap1.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 659)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 1021, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(260, -10, 531, 61))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 230, 1021, 371))
        self.frame_3.setStyleSheet("QFrame#frame_3 {\n"
"    background-color: #D8EAF5;      /* Xanh siêu nhạt, nhẹ hơn #A7C7E7 */\n"
"    border: 2px solid #336699;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tablemonan = QtWidgets.QTableWidget(parent=self.frame_3)
        self.tablemonan.setGeometry(QtCore.QRect(20, 120, 981, 241))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tablemonan.setFont(font)
        self.tablemonan.setStyleSheet("QTableWidget {\n"
"    background-color: #F7FBFF;      /* nền bảng trắng xanh */\n"
"    color: #000000;   \n"
"    gridline-color: #B0C4DE;        /* màu kẻ ô */\n"
"    border: 1px solid #99BADD;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #A7C7E7;      /* header xanh nhạt như hình */\n"
"    color: #000;\n"
"    font-weight: bold;\n"
"    padding: 4px 6px;\n"
"    border: 1px solid #336699;\n"
"}\n"
"\n"
"/* hover chọn dòng nhìn rõ hơn */\n"
"QTableWidget::item:selected {\n"
"    background: #D6EAF8;\n"
"}\n"
"")
        self.tablemonan.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tablemonan.setAlternatingRowColors(True)
        self.tablemonan.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tablemonan.setObjectName("tablemonan")
        self.tablemonan.setColumnCount(3)
        self.tablemonan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tablemonan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablemonan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablemonan.setHorizontalHeaderItem(2, item)
        self.tablemonan.horizontalHeader().setDefaultSectionSize(250)
        self.tablemonan.horizontalHeader().setStretchLastSection(True)
        self.lbl_header_timkiem_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.lbl_header_timkiem_2.setGeometry(QtCore.QRect(0, 0, 1021, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Roboto,Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header_timkiem_2.setFont(font)
        self.lbl_header_timkiem_2.setStyleSheet("QLabel#lbl_header_timkiem_2 {\n"
"    background-color: #336699;   /* Màu xanh đậm */\n"
"    color: white;                /* Chữ trắng */\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\", \"Roboto\", \"Arial\";\n"
"    font-size: 10pt;\n"
"    padding: 6px;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"}\n"
"")
        self.lbl_header_timkiem_2.setObjectName("lbl_header_timkiem_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame_3)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 981, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #F7FBFF;         /* xanh cực nhạt */\n"
"    border: 1px solid #99BADD;         /* viền xanh nhạt */\n"
"    border-radius: 6px;\n"
"    margin-top: 8px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 4px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: normal;\n"
"    color: #000000;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 911, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hiennlchinh = QtWidgets.QLabel(parent=self.groupBox)
        self.hiennlchinh.setGeometry(QtCore.QRect(30, 20, 909, 50))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        self.hiennlchinh.setFont(font)
        self.hiennlchinh.setObjectName("hiennlchinh")
        self.frame_timkiem = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_timkiem.setGeometry(QtCore.QRect(20, 70, 1021, 151))
        self.frame_timkiem.setStyleSheet("QFrame#frame_timkiem {\n"
"    background-color: #D8EAF5;      /* Xanh siêu nhạt, nhẹ hơn #A7C7E7 */\n"
"    border: 2px solid #336699;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}")
        self.frame_timkiem.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_timkiem.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_timkiem.setObjectName("frame_timkiem")
        self.lbl_header_timkiem = QtWidgets.QLabel(parent=self.frame_timkiem)
        self.lbl_header_timkiem.setGeometry(QtCore.QRect(0, 0, 1021, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Roboto,Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header_timkiem.setFont(font)
        self.lbl_header_timkiem.setStyleSheet("QLabel#lbl_header_timkiem {\n"
"    background-color: #336699;   /* Màu xanh đậm */\n"
"    color: white;                /* Chữ trắng */\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\", \"Roboto\", \"Arial\";\n"
"    font-size: 10pt;\n"
"    padding: 6px;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"}\n"
"")
        self.lbl_header_timkiem.setObjectName("lbl_header_timkiem")
        self.pushtinh = QtWidgets.QPushButton(parent=self.frame_timkiem)
        self.pushtinh.setGeometry(QtCore.QRect(450, 110, 121, 31))
        self.pushtinh.setStyleSheet("")
        self.pushtinh.setObjectName("pushtinh")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frame_timkiem)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 971, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(4, 11, 8, 7)
        self.gridLayout.setObjectName("gridLayout")
        self.nguyenlieuchinh = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nguyenlieuchinh.setFont(font)
        self.nguyenlieuchinh.setObjectName("nguyenlieuchinh")
        self.gridLayout.addWidget(self.nguyenlieuchinh, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Food recommendation system"))
        item = self.tablemonan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tên món ăn"))
        item = self.tablemonan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nguyên liệu chính"))
        item = self.tablemonan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nguyên liệu phụ"))
        self.lbl_header_timkiem_2.setText(_translate("MainWindow", "GỢI Ý MÓN ĂN"))
        self.groupBox.setTitle(_translate("MainWindow", "NGUYÊN LIỆU ĐÃ NHẬN DIỆN"))
        self.hiennlchinh.setText(_translate("MainWindow", "Nguyên liệu : "))
        self.lbl_header_timkiem.setText(_translate("MainWindow", "TÌM KIẾM MÓN ĂN"))
        self.pushtinh.setText(_translate("MainWindow", "Tìm kiếm"))
        self.nguyenlieuchinh.setPlaceholderText(_translate("MainWindow", "ví dụ: thịt lợn, gà, rau cải, cà pháo,..."))
        self.label_2.setText(_translate("MainWindow", "Nguyên liệu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
